// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk46l-bkfFExTf-Vf6pNAQnxN2mp48jEI',
    appId: '1:50264098849:web:16544735239f897d577b60',
    messagingSenderId: '50264098849',
    projectId: 'talatna-3d71f',
    authDomain: 'talatna-3d71f.firebaseapp.com',
    storageBucket: 'talatna-3d71f.appspot.com',
    measurementId: 'G-Y8166440YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdAyPmncgtSc3VTP9HSrGFAPzQQO1mSJ4',
    appId: '1:50264098849:android:6adf16feb6ad027a577b60',
    messagingSenderId: '50264098849',
    projectId: 'talatna-3d71f',
    storageBucket: 'talatna-3d71f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz0TeST6nel2YiQAOhseT2I8likEYmZ68',
    appId: '1:50264098849:ios:ad6ec72646afa659577b60',
    messagingSenderId: '50264098849',
    projectId: 'talatna-3d71f',
    storageBucket: 'talatna-3d71f.appspot.com',
    iosClientId: '50264098849-mbububpq7h5ffm49cim11gd91abm35st.apps.googleusercontent.com',
    iosBundleId: 'com.example.talatna1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz0TeST6nel2YiQAOhseT2I8likEYmZ68',
    appId: '1:50264098849:ios:ad6ec72646afa659577b60',
    messagingSenderId: '50264098849',
    projectId: 'talatna-3d71f',
    storageBucket: 'talatna-3d71f.appspot.com',
    iosClientId: '50264098849-mbububpq7h5ffm49cim11gd91abm35st.apps.googleusercontent.com',
    iosBundleId: 'com.example.talatna1',
  );
}
